# Generated by Django 5.0.14 on 2026-05-15 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_buyer_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='last_name',
        ),
    ]
