# Generated by Django 5.0.14 on 2026-05-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_book_authors_alter_product_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
