# Generated by Django 5.0.14 on 2026-05-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
