# Generated by Django 5.0.14 on 2026-05-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В обработке'), ('paid', 'Оплачен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
